### ISSUE TITLE
Ps.initialize is not a function 

### ISSUE THREAD

**Issue by filipvh** [zefoy/ngx-perfect-scrollbar#96]
in my angular-cli project
perfect-scrollbar is in node-modules folder
did the setup in module
imported the css
![image](https://user-images.githubusercontent.com/6095002/31609342-072981fc-b274-11e7-97a5-764e634b52ae.png)

**Comment by sconix** [comment]
What are your angular-cli, npm, perfect-scrollbar, ngx-perfect-scrollbar versions?

**Comment by filipvh** [comment]
npm 3.10.10
angular/cli: 1.3.2
ngx-perfect-scrollbar: 4.9.0
perfect-scrollbar: 1.0.3

**Comment by sconix** [comment]
Ok this seems to be due to the just release 4.9.0 which seems to have some old code left. I wonder why my test setup did not pick this, weird. Will release 4.9.1 really soon that fixes this.

**Comment by filipvh** [comment]
@sconix thanks for the quick response

**Comment by sconix** [comment]
In my test setup I had forgot to update perfect-scrollbar so no wonder it worked :) I reverted the latest tag to point to last working version (4.8.4) which uses the older 0.8.x perfect scrollbar.

I will also soon release 4.9.1 that fixes the above issue under beta tag since I noticed a small bug with the perfect-scrollbar 1.0.3 which I will wait to get fixed before making 4.9.x the latest.

**Comment by munkk** [comment]
@sconix hello, please leave a message here when this issue will be resolved

**Comment by sconix** [comment]
Will do, the 4.9.1 which is now released with beta tag should work, but the issue in perfect-scrollbar 1.0.3 will render some features as none working such as the scroll indicators. Basic stuff should however work. I will notify here once fully working release is out, until that its safer to use 4.8.4, but those who really want the 1.x already then the beta version can be used.

**Comment by fpmk** [comment]
I have the same issue.
```
"ngx-perfect-scrollbar": "^5.0.0-8",
"@angular/cli": "^1.5.0-rc.8"
```

**Comment by sconix** [comment]
Check the npm info, use only tagged versions. Both 4.9.0/1 and 5.0.0-8 are none functional pre-releases which use perfect-scrollbar 1.x. Still waiting for new release of perfect-scrollbar with needed fixes so that I can release fully working versions.

**Comment by fpmk** [comment]
Perfect-scrollbar changed declaration for typescript. Now there is no methods like initialize(elem, options), update(smth), destroy(smth)
We need to create new PerfectScrollbar instance with params (elem, options). Then call methods update(), destroy() to created instance. Maybe you could check and fix scrollbar-directive?

**Comment by sconix** [comment]
As I said above the version that works with PS 1.x is coming, currently you need to use version 0.8.x. I have new release ready and its only waiting for new PS release so that everything works, required fixes has been merged to PS, but they have not yet been released.

**Comment by alaindeurveilher** [comment]
Hi, yes. But the problem is that these versions are not compatible with Angular 5 which deprecated the opakeToken and still used in 4.8.4. Isn't there any possibility to have a middle version released with just compatibility with Angular 5 ? Thank you.

**Comment by sconix** [comment]
Therr is Angular 5 compatible version: 5.0.0-7

**Comment by alaindeurveilher** [comment]
Hi, thank you. Yes, I know, I am trying to update to 5.0.0-8. But they all have the Ps.initialize issue. That is why I was just wondering if in the meantime, we could have a 4.8.5 or something with just the PR which uses the InjectionToken instead of the deprecated OpaqueToken ?

**Comment by sconix** [comment]
As i said the version is 5.0.0-7 not -8.

**Comment by sconix** [comment]
I have updated both code bases 4.x and 5.x to PS 1.0 so I would not want to go messings things more to go back to 0.8 specially since there is working releases and all I need is new release from PS and I can then release the new official releases.

So just saying it once morr, @latest npm release is for Angular 4.x and @next (5.0.0-7) release for Angular 5.x bot uses PS 0.8 and therefore are in working state.

**Comment by aissam-ahbar** [comment]
Hi guys,
I still have the issue "Ps.initialize is not a function" at eval (perfect-scrollbar.directive.js:78) after upgrading from angular 4.4.5 to 5.0.0.

Here is my setup:
npm 5.4.2
angular/cli: 1.5.0
ngx-perfect-scrollbar: 5.0.0-8
perfect-scrollbar: 1.1.0

# html
```
<perfect-scrollbar [config]="config"> 
    ...
</perfect-scrollbar>
```
 
# typescript
```
export class MenuComponent implements OnInit {
  public config = {wheelSpeed: 2, suppressScrollX: true};
}
```

# module 
```
import { PerfectScrollbarConfigInterface, PerfectScrollbarModule } from 'ngx-perfect-scrollbar';

const PERFECT_SCROLLBAR_CONFIG: PerfectScrollbarConfigInterface = {
  suppressScrollX: true
};

@NgModule({
...
  imports: [
    PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG),
  ], 
 ...

```

I tried to change the dependencies many times with different versions of perfect-scrollbar but none of them seems working with Angular 5.

Any idea?

**Comment by sconix** [comment]
Just read carefully my previous comment.

**Comment by aissam-ahbar** [comment]
Ok, I guess I need to wait till the new release comes as the following did not solve:
- Use the ngx-perfect-scrollbar  version "5.0.0-7"
- Use PS version "0.8.0"

**Comment by alaindeurveilher** [comment]
Hi,
Apparently you won't need to specifically use PS 0.8 as NPS 5.0.0-7 already depends on it:
`"perfect-scrollbar": "^0.8.0"` in its dependencies

**Comment by aissam-ahbar** [comment]
You are right Alain, I removed it from my dependencies as it is already included. 

Anyway, using  ngx-perfect-scrollbar version "5.0.0-7" still raises the same issue: 

```
ERROR TypeError: Ps.initialize is not a function
    at eval (perfect-scrollbar.directive.js:78)
    at ZoneDelegate.invoke (zone.js:392)
    at Zone.run (zone.js:142)
    at NgZone.runOutsideAngular (core.js:4574)
    at PerfectScrollbarDirective.ngAfterViewInit (perfect-scrollbar.directive.js:77)
    at callProviderLifecycles (core.js:12427)
    at callElementProvidersLifecycles (core.js:12398)
    at callLifecycleHooksChildrenFirst (core.js:12382)
    at checkAndUpdateView (core.js:13515)
    at callViewAction (core.js:13857)
```

**Comment by sconix** [comment]
That error definitely tells that you still have perfect-scrollbar 1.x installed and not the 0.8.x which is the dependency of the 5.0.0-7.

**Comment by aissam-ahbar** [comment]
Thanks for the information.

However, I do not understand the reason why I get this error because in my dependencies, I have the following:

If I list what npm has installed, I can see this:
  "dependencies": {
    "ngx-perfect-scrollbar": "^5.0.0-7",
    "perfect-scrollbar": "^0.8.0",
    ...
}

npm list --depth=0
```
├── @angular/cli@1.5.0
├── ngx-perfect-scrollbar@5.0.0-8
├── perfect-scrollbar@0.8.0
```

I removed PS then reinstalled it, does not change the result. 

Anyway, thanks for your help.

**Comment by j2L4e** [comment]
You should read up on npm's versioning.

change `"ngx-perfect-scrollbar": "^5.0.0-7"` to `"ngx-perfect-scrollbar": "5.0.0-7"`

**Comment by aissam-ahbar** [comment]
Thanks a lot, this solves the issue. Great job!

**Comment by sconix** [comment]
I just released 4.9.2 which uses PS 1.x (1.2.0 required) and is fully working. New pre-release for Angular 5 (5.0.0-9) is coming really soon (at the latest tomorrow).

**Comment by vvc29091993** [comment]
Hi team, I am facing this issue please help me.

Error: no element is specified to initialize PerfectScrollbar


"@angular/animations": "^6.0.7",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/flex-layout": "^6.0.0-beta.16",
    "@angular/forms": "^6.0.3",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "ngx-infinite-scroll": "^6.0.1",
    "ngx-perfect-scrollbar": "^6.2.0",
    "perfect-scrollbar": "^1.4.0",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
